# Homework 4 - Functions II

In [1]:

import pandas as pd
import numpy as np
import statsmodels.api as sm
from random import randint
from math import sqrt

## Q1. Split data into categorical, numeric, and boolean datasets

In [2]:
df = pd.read_csv("Data/Housing_prices_data.csv")
print(f"Full dataset shape: {df.shape}")
df.head()

Full dataset shape: (1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
# Categorical
df_cat = df.select_dtypes(include=['object'])

# Numeric
df_num = df.select_dtypes(include=['int64', 'float64'])

# Boolean
df_bool = df.select_dtypes(include=['bool'])

print(f"Categorical dataset shape: {df_cat.shape}")
print(f"Numeric dataset shape: {df_num.shape}")
print(f"Boolean dataset shape: {df_bool.shape}")
print(f"\nCategorical columns: {list(df_cat.columns)}")
print(f"\nNumeric columns: {list(df_num.columns)}")
print(f"\nBoolean columns: {list(df_bool.columns)}")

Categorical dataset shape: (1460, 42)
Numeric dataset shape: (1460, 38)
Boolean dataset shape: (1460, 1)

Categorical columns: ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

Numeric columns: ['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

Boolean columns: ['CentralAir']

/var/folders/m_/tx6g14_s1tq5t5ws7rlvzc0w0000gn/T/ipykernel_88996/3016889126.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_cat = df.select_dtypes(include=['object'])

In [ ]:
# first and last 5 rows
print("=== Categorical Dataset ===")
print("First 5 rows:")
display(df_cat.head())
print("\nLast 5 rows:")
display(df_cat.tail())

print("\n=== Numeric Dataset ===")
print("First 5 rows:")
display(df_num.head())
print("\nLast 5 rows:")
display(df_num.tail())

print("\n=== Boolean Dataset ===")
print("First 5 rows:")
display(df_bool.head())
print("\nLast 5 rows:")
display(df_bool.tail())

=== Categorical Dataset ===
First 5 rows:

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

Last 5 rows:

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

=== Numeric Dataset ===
First 5 rows:

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

Last 5 rows:

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

=== Boolean Dataset ===
First 5 rows:

   CentralAir
0        True
1        True
2        True
3        True
4        True

Last 5 rows:

      CentralAir
1455        True
1456        True
1457        True
1458        True
1459        True

## Q2. Mean, Median, and SD for all numeric variables using apply

In [ ]:
summary_stats = df_num.apply(lambda x: pd.Series({
    'Mean': x.mean(),
    'Median': x.median(),
    'SD': x.std()
}))

print("First 5 columns:")
display(summary_stats.iloc[:, :5])
print("\nLast 5 columns:")
display(summary_stats.iloc[:, -5:])

First 5 columns:

                Id  MSSubClass  LotFrontage       LotArea  OverallQual
Mean    730.500000   56.897260    70.049958  10516.828082     6.099315
Median  730.500000   50.000000    69.000000   9478.500000     6.000000
SD      421.610009   42.300571    24.284752   9981.264932     1.382997

Last 5 columns:

         PoolArea     MiscVal    MoSold       YrSold      SalePrice
Mean     2.758904   43.489041  6.321918  2007.815753  180921.195890
Median   0.000000    0.000000  6.000000  2008.000000  163000.000000
SD      40.177307  496.123024  2.703626     1.328095   79442.502883

## Q3. SalePrice grouped by a categorical variable (2-4 categories)

In [6]:
print("Categorical variables with 2-4 unique categories:")
for col in df_cat.columns:
    n_unique = df_cat[col].nunique()
    if 2 <= n_unique <= 4:
        print(f"  {col}: {n_unique} categories -> {df_cat[col].unique()}")

Categorical variables with 2-4 unique categories:
  Street: 2 categories -> <StringArray>
['Pave', 'Grvl']
Length: 2, dtype: str
  Alley: 2 categories -> <StringArray>
[nan, 'Grvl', 'Pave']
Length: 3, dtype: str
  LotShape: 4 categories -> <StringArray>
['Reg', 'IR1', 'IR2', 'IR3']
Length: 4, dtype: str
  LandContour: 4 categories -> <StringArray>
['Lvl', 'Bnk', 'Low', 'HLS']
Length: 4, dtype: str
  Utilities: 2 categories -> <StringArray>
['AllPub', 'NoSeWa']
Length: 2, dtype: str
  LandSlope: 3 categories -> <StringArray>
['Gtl', 'Mod', 'Sev']
Length: 3, dtype: str
  MasVnrType: 3 categories -> <StringArray>
['BrkFace', nan, 'Stone', 'BrkCmn']
Length: 4, dtype: str
  ExterQual: 4 categories -> <StringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
  BsmtQual: 4 categories -> <StringArray>
['Gd', 'TA', 'Ex', nan, 'Fa']
Length: 5, dtype: str
  BsmtCond: 4 categories -> <StringArray>
['TA', 'Gd', nan, 'Fa', 'Po']
Length: 5, dtype: str
  BsmtExposure: 4 categories -> <StringArray>
['No', 'Gd', 'Mn', 'Av', nan]
Length: 5, dtype: str
  KitchenQual: 4 categories -> <StringArray>
['Gd', 'TA', 'Ex', 'Fa']
Length: 4, dtype: str
  GarageFinish: 3 categories -> <StringArray>
['RFn', 'Unf', 'Fin', nan]
Length: 4, dtype: str
  PavedDrive: 3 categories -> <StringArray>
['Y', 'N', 'P']
Length: 3, dtype: str
  PoolQC: 3 categories -> <StringArray>
[nan, 'Ex', 'Fa', 'Gd']
Length: 4, dtype: str
  Fence: 4 categories -> <StringArray>
[nan, 'MnPrv', 'GdWo', 'GdPrv', 'MnWw']
Length: 5, dtype: str
  MiscFeature: 4 categories -> <StringArray>
[nan, 'Shed', 'Gar2', 'Othr', 'TenC']
Length: 5, dtype: str

In [7]:
# Choose LandContour (flatness of the property) - 4 categories, likely related to SalePrice
# Create SalePrice dataset
df_saleprice = df_num[["SalePrice"]]

# Combine SalePrice with the chosen categorical variable
df_combined = pd.concat([df_saleprice, df[["LandContour"]]], axis=1)

# Mean, Median, SD of SalePrice grouped by LandContour
grouped_stats = df_combined.groupby("LandContour")["SalePrice"].agg(["mean", "median", "std"])
grouped_stats.columns = ["Mean", "Median", "SD"]
print("SalePrice statistics by LandContour:")
display(grouped_stats)

print("\nYes, the average sale price appears to vary by land contour.")
print("Properties that are near flat/level (Lvl) or hillside (HLS) tend to have")
print("different average prices compared to those on banked (Bnk) or low depression (Low) lots.")

SalePrice statistics by LandContour:

                      Mean    Median             SD
LandContour
Bnk          143104.079365  139400.0   49361.244074
HLS          231533.940000  222250.0  101790.139741
Low          203661.111111  190000.0   83935.353620
Lvl          180183.746758  162900.0   78463.567918

Yes, the average sale price appears to vary by land contour.
Properties that are near flat/level (Lvl) or hillside (HLS) tend to have
different average prices compared to those on banked (Bnk) or low depression (Low) lots.

## Q4. Regress SalePrice on LotArea, OverallQual, OverallCond

In [8]:
import statsmodels.api as sm

# Specify DVs and IVs
x = df_num[['LotArea', 'OverallQual', 'OverallCond']]
y = (df_num["SalePrice"])
x = sm.add_constant(x)

# fit linear regression model
model = sm.OLS(y, x).fit()

# view model summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.658
Method:                 Least Squares   F-statistic:                     935.9
Date:                Thu, 26 Mar 2026   Prob (F-statistic):               0.00
Time:                        13:04:17   Log-Likelihood:                -17760.
No. Observations:                1460   AIC:                         3.553e+04
Df Residuals:                    1456   BIC:                         3.555e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.022e+05   8633.073    -11.832      0.000   -1.19e+05   -8.52e+04
LotArea         1.4503      0.123     11.831      0.000       1.210       1.691
OverallQual   4.43e+04    888.434     49.860      0.000    4.26e+04     4.6e+04
OverallCond  -423.6737   1097.973     -0.386      0.700   -2577.451    1730.104
==============================================================================
Omnibus:                      574.483   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7330.883
Skew:                           1.468   Prob(JB):                         0.00
Kurtosis:                      13.578   Cond. No.                     1.04e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

## Q5. For loop: Regression by each level of the categorical variable

In [9]:
# Get unique 
categories = df["LandContour"].unique()
print(f"Categories: {categories}\n")
model_summaries = []

for cat in categories:
    subset = df[df["LandContour"] == cat]
    
    # regression
    x = subset[['LotArea', 'OverallQual', 'OverallCond']]
    y = subset["SalePrice"]
    x = sm.add_constant(x)
    
    # fit model
    model = sm.OLS(y, x).fit()
    model_summaries.append(model.summary())

for i, summary in enumerate(model_summaries):
    print(f"\n{'='*60}")
    print(f"Regression for LandContour = {categories[i]}")
    print(f"{'='*60}")
    print(summary)
    print("\n")

Categories: <StringArray>
['Lvl', 'Bnk', 'Low', 'HLS']
Length: 4, dtype: str


============================================================
Regression for LandContour = Lvl
============================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.709
Model:                            OLS   Adj. R-squared:                  0.708
Method:                 Least Squares   F-statistic:                     1059.
Date:                Thu, 26 Mar 2026   Prob (F-statistic):               0.00
Time:                        13:04:19   Log-Likelihood:                -15827.
No. Observations:                1311   AIC:                         3.166e+04
Df Residuals:                    1307   BIC:                         3.168e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.322e+05   8636.299    -15.307      0.000   -1.49e+05   -1.15e+05
LotArea         5.0518      0.295     17.120      0.000       4.473       5.631
OverallQual  4.324e+04    894.712     48.327      0.000    4.15e+04     4.5e+04
OverallCond   -83.2282   1062.925     -0.078      0.938   -2168.454    2001.997
==============================================================================
Omnibus:                      589.281   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7451.422
Skew:                           1.741   Prob(JB):                         0.00
Kurtosis:                      14.149   Cond. No.                     7.77e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.77e+04. This might indicate that there are
strong multicollinearity or other numerical problems.



============================================================
Regression for LandContour = Bnk
============================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.424
Model:                            OLS   Adj. R-squared:                  0.395
Method:                 Least Squares   F-statistic:                     14.47
Date:                Thu, 26 Mar 2026   Prob (F-statistic):           3.56e-07
Time:                        13:04:19   Log-Likelihood:                -752.36
No. Observations:                  63   AIC:                             1513.
Df Residuals:                      59   BIC:                             1521.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -3.662e+04   2.97e+04     -1.234      0.222    -9.6e+04    2.28e+04
LotArea         0.9683      0.470      2.061      0.044       0.028       1.908
OverallQual  1.128e+04   4036.307      2.795      0.007    3205.987    1.94e+04
OverallCond  1.788e+04   4402.343      4.062      0.000    9071.281    2.67e+04
==============================================================================
Omnibus:                        1.868   Durbin-Watson:                   2.119
Prob(Omnibus):                  0.393   Jarque-Bera (JB):                1.183
Skew:                           0.299   Prob(JB):                        0.553
Kurtosis:                       3.303   Cond. No.                     1.02e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.02e+05. This might indicate that there are
strong multicollinearity or other numerical problems.



============================================================
Regression for LandContour = Low
============================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.845
Model:                            OLS   Adj. R-squared:                  0.831
Method:                 Least Squares   F-statistic:                     58.27
Date:                Thu, 26 Mar 2026   Prob (F-statistic):           4.61e-13
Time:                        13:04:19   Log-Likelihood:                -425.15
No. Observations:                  36   AIC:                             858.3
Df Residuals:                      32   BIC:                             864.6
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -8336.2151   2.54e+04     -0.328      0.745   -6.01e+04    4.34e+04
LotArea         0.7229      0.135      5.360      0.000       0.448       0.998
OverallQual  3.793e+04   3797.496      9.989      0.000    3.02e+04    4.57e+04
OverallCond -5233.7849   4751.950     -1.101      0.279   -1.49e+04    4445.620
==============================================================================
Omnibus:                        7.102   Durbin-Watson:                   2.172
Prob(Omnibus):                  0.029   Jarque-Bera (JB):                5.783
Skew:                           0.758   Prob(JB):                       0.0555
Kurtosis:                       4.247   Cond. No.                     2.44e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.



============================================================
Regression for LandContour = HLS
============================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.684
Model:                            OLS   Adj. R-squared:                  0.663
Method:                 Least Squares   F-statistic:                     33.16
Date:                Thu, 26 Mar 2026   Prob (F-statistic):           1.45e-11
Time:                        13:04:19   Log-Likelihood:                -618.19
No. Observations:                  50   AIC:                             1244.
Df Residuals:                      46   BIC:                             1252.
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.192e+05   8.55e+04     -1.394      0.170   -2.91e+05    5.29e+04
LotArea         1.1318      0.370      3.055      0.004       0.386       1.877
OverallQual   5.24e+04   5934.065      8.830      0.000    4.05e+04    6.43e+04
OverallCond -4679.6219   1.07e+04     -0.438      0.663   -2.62e+04    1.68e+04
==============================================================================
Omnibus:                        9.943   Durbin-Watson:                   2.315
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               10.859
Skew:                           0.757   Prob(JB):                      0.00438
Kurtosis:                       4.709   Cond. No.                     2.83e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.83e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

**Does the effect of LotArea on SalePrice vary within the different levels of LandContour?**

Yes, the coefficient for LotArea differs across the LandContour groups. To properly compare, we need to consider both the coefficient and its standard error. If the confidence intervals for the LotArea coefficient do not overlap across groups.

**What is another, more common way to answer a question like this?**

A more common approach is to include an interaction term between LotArea and LandContour in a single regression model. This tests whether the relationship between LotArea and SalePrice is moderated by LandContour.

## Q6. For loop: Frequency and relative frequency tables for categorical variables

In [10]:
# For loop
for col in df_cat.columns:
    print(f"Frequency table for {col}===============")
    freq = df_cat[col].value_counts()
    print(freq)
    
    # frequency
    print(f"\nRelative Frequency table for {col}===============")
    rel_freq = df_cat[col].value_counts(normalize=True)
    print(rel_freq)

Frequency table for MSZoning===============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative Frequency table for MSZoning===============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64
Frequency table for Street===============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative Frequency table for Street===============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64
Frequency table for Alley===============
Alley
Grvl    50
Pave    41
Name: count, dtype: int64

Relative Frequency table for Alley===============
Alley
Grvl    0.549451
Pave    0.450549
Name: proportion, dtype: float64
Frequency table for LotShape===============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative Frequency table for LotShape===============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64
Frequency table for LandContour===============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative Frequency table for LandContour===============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64
Frequency table for Utilities===============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative Frequency table for Utilities===============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64
Frequency table for LotConfig===============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative Frequency table for LotConfig===============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64
Frequency table for LandSlope===============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative Frequency table for LandSlope===============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64
Frequency table for Neighborhood===============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative Frequency table for Neighborhood===============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
StoneBr    0.017123
SWISU      0.017123
MeadowV    0.011644
Blmngtn    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64
Frequency table for Condition1===============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative Frequency table for Condition1===============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64
Frequency table for Condition2===============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative Frequency table for Condition2===============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64
Frequency table for BldgType===============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative Frequency table for BldgType===============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64
Frequency table for HouseStyle===============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative Frequency table for HouseStyle===============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64
Frequency table for RoofStyle===============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative Frequency table for RoofStyle===============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64
Frequency table for RoofMatl===============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative Frequency table for RoofMatl===============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64
Frequency table for Exterior1st===============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative Frequency table for Exterior1st===============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64
Frequency table for Exterior2nd===============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative Frequency table for Exterior2nd===============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64
Frequency table for MasVnrType===============
MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative Frequency table for MasVnrType===============
MasVnrType
BrkFace    0.756803
Stone      0.217687
BrkCmn     0.025510
Name: proportion, dtype: float64
Frequency table for ExterQual===============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative Frequency table for ExterQual===============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64
Frequency table for ExterCond===============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative Frequency table for ExterCond===============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64
Frequency table for Foundation===============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative Frequency table for Foundation===============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64
Frequency table for BsmtQual===============
BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

Relative Frequency table for BsmtQual===============
BsmtQual
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: proportion, dtype: float64
Frequency table for BsmtCond===============
BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

Relative Frequency table for BsmtCond===============
BsmtCond
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: proportion, dtype: float64
Frequency table for BsmtExposure===============
BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

Relative Frequency table for BsmtExposure===============
BsmtExposure
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: proportion, dtype: float64
Frequency table for BsmtFinType1===============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

Relative Frequency table for BsmtFinType1===============
BsmtFinType1
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: proportion, dtype: float64
Frequency table for BsmtFinType2===============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative Frequency table for BsmtFinType2===============
BsmtFinType2
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: proportion, dtype: float64
Frequency table for Heating===============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative Frequency table for Heating===============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64
Frequency table for HeatingQC===============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative Frequency table for HeatingQC===============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64
Frequency table for Electrical===============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

Relative Frequency table for Electrical===============
Electrical
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: proportion, dtype: float64
Frequency table for KitchenQual===============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative Frequency table for KitchenQual===============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64
Frequency table for Functional===============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative Frequency table for Functional===============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64
Frequency table for FireplaceQu===============
FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

Relative Frequency table for FireplaceQu===============
FireplaceQu
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: proportion, dtype: float64
Frequency table for GarageType===============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative Frequency table for GarageType===============
GarageType
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: proportion, dtype: float64
Frequency table for GarageFinish===============
GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

Relative Frequency table for GarageFinish===============
GarageFinish
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: proportion, dtype: float64
Frequency table for GarageQual===============
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

Relative Frequency table for GarageQual===============
GarageQual
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: proportion, dtype: float64
Frequency table for GarageCond===============
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

Relative Frequency table for GarageCond===============
GarageCond
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: proportion, dtype: float64
Frequency table for PavedDrive===============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative Frequency table for PavedDrive===============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64
Frequency table for PoolQC===============
PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

Relative Frequency table for PoolQC===============
PoolQC
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: proportion, dtype: float64
Frequency table for Fence===============
Fence
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: count, dtype: int64

Relative Frequency table for Fence===============
Fence
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: proportion, dtype: float64
Frequency table for MiscFeature===============
MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

Relative Frequency table for MiscFeature===============
MiscFeature
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: proportion, dtype: float64
Frequency table for SaleType===============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative Frequency table for SaleType===============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64
Frequency table for SaleCondition===============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative Frequency table for SaleCondition===============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

## Q7. While loop: Frequency and relative frequency tables for categorical variables

In [11]:
# While loop
i = 0
cat_columns = list(df_cat.columns)

while i < len(cat_columns):
    col = cat_columns[i]
    
    print(f"Frequency table for {col}===============")
    freq = df_cat[col].value_counts()
    print(freq)
    
    print(f"\nRelative Frequency table for {col}===============")
    rel_freq = df_cat[col].value_counts(normalize=True)
    print(rel_freq)
    
    print("\n\n")
    
    i += 1

Frequency table for MSZoning===============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative Frequency table for MSZoning===============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64



Frequency table for Street===============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative Frequency table for Street===============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64



Frequency table for Alley===============
Alley
Grvl    50
Pave    41
Name: count, dtype: int64

Relative Frequency table for Alley===============
Alley
Grvl    0.549451
Pave    0.450549
Name: proportion, dtype: float64



Frequency table for LotShape===============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative Frequency table for LotShape===============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64



Frequency table for LandContour===============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative Frequency table for LandContour===============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64



Frequency table for Utilities===============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative Frequency table for Utilities===============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64



Frequency table for LotConfig===============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative Frequency table for LotConfig===============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64



Frequency table for LandSlope===============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative Frequency table for LandSlope===============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64



Frequency table for Neighborhood===============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative Frequency table for Neighborhood===============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
StoneBr    0.017123
SWISU      0.017123
MeadowV    0.011644
Blmngtn    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64



Frequency table for Condition1===============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative Frequency table for Condition1===============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64



Frequency table for Condition2===============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative Frequency table for Condition2===============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64



Frequency table for BldgType===============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative Frequency table for BldgType===============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64



Frequency table for HouseStyle===============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative Frequency table for HouseStyle===============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64



Frequency table for RoofStyle===============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative Frequency table for RoofStyle===============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64



Frequency table for RoofMatl===============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative Frequency table for RoofMatl===============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64



Frequency table for Exterior1st===============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative Frequency table for Exterior1st===============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for Exterior2nd===============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative Frequency table for Exterior2nd===============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64



Frequency table for MasVnrType===============
MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative Frequency table for MasVnrType===============
MasVnrType
BrkFace    0.756803
Stone      0.217687
BrkCmn     0.025510
Name: proportion, dtype: float64



Frequency table for ExterQual===============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative Frequency table for ExterQual===============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64



Frequency table for ExterCond===============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative Frequency table for ExterCond===============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Foundation===============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative Frequency table for Foundation===============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64



Frequency table for BsmtQual===============
BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

Relative Frequency table for BsmtQual===============
BsmtQual
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: proportion, dtype: float64



Frequency table for BsmtCond===============
BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

Relative Frequency table for BsmtCond===============
BsmtCond
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: proportion, dtype: float64



Frequency table for BsmtExposure===============
BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

Relative Frequency table for BsmtExposure===============
BsmtExposure
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: proportion, dtype: float64



Frequency table for BsmtFinType1===============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

Relative Frequency table for BsmtFinType1===============
BsmtFinType1
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: proportion, dtype: float64



Frequency table for BsmtFinType2===============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative Frequency table for BsmtFinType2===============
BsmtFinType2
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: proportion, dtype: float64



Frequency table for Heating===============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative Frequency table for Heating===============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64



Frequency table for HeatingQC===============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative Frequency table for HeatingQC===============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64



Frequency table for Electrical===============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

Relative Frequency table for Electrical===============
Electrical
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: proportion, dtype: float64



Frequency table for KitchenQual===============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative Frequency table for KitchenQual===============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64



Frequency table for Functional===============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative Frequency table for Functional===============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64



Frequency table for FireplaceQu===============
FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

Relative Frequency table for FireplaceQu===============
FireplaceQu
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: proportion, dtype: float64



Frequency table for GarageType===============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative Frequency table for GarageType===============
GarageType
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: proportion, dtype: float64



Frequency table for GarageFinish===============
GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

Relative Frequency table for GarageFinish===============
GarageFinish
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: proportion, dtype: float64



Frequency table for GarageQual===============
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

Relative Frequency table for GarageQual===============
GarageQual
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: proportion, dtype: float64



Frequency table for GarageCond===============
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

Relative Frequency table for GarageCond===============
GarageCond
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: proportion, dtype: float64



Frequency table for PavedDrive===============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative Frequency table for PavedDrive===============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64



Frequency table for PoolQC===============
PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

Relative Frequency table for PoolQC===============
PoolQC
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: proportion, dtype: float64



Frequency table for Fence===============
Fence
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: count, dtype: int64

Relative Frequency table for Fence===============
Fence
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: proportion, dtype: float64



Frequency table for MiscFeature===============
MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

Relative Frequency table for MiscFeature===============
MiscFeature
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: proportion, dtype: float64



Frequency table for SaleType===============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative Frequency table for SaleType===============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64



Frequency table for SaleCondition===============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative Frequency table for SaleCondition===============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

## Q8. Shuttle class inheriting from Rocket class

In [12]:

class Rocket:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
    
    def move_rocket(self, x_increment=0, y_increment=1):
        self.x += x_increment
        self.y += y_increment
    
    def get_distance(self, other_rocket):
        distance = sqrt((self.x - other_rocket.x)**2 + (self.y - other_rocket.y)**2)
        return distance


# Define shuttle
class Shuttle(Rocket):
    def __init__(self, x=0, y=0, flights_completed=0):
        super().__init__(x, y)
        self.flights_completed = flights_completed


# Init
my_shuttle = Shuttle(x=5, y=10, flights_completed=3)
print(f"The shuttle is located at ({my_shuttle.x}, {my_shuttle.y}), and has recorded {my_shuttle.flights_completed} flights.")

The shuttle is located at (5, 10), and has recorded 3 flights.

## Q9. Randomly create 11 Rockets and 11 Shuttles

In [13]:
from random import randint

rockets = []
shuttles = []

for i in range(11):
    rockets.append(Rocket(x=randint(0, 100), y=randint(0, 100)))
    shuttles.append(Shuttle(x=randint(0, 100), y=randint(0, 100), flights_completed=randint(0, 10)))

In [14]:

for i, shuttle in enumerate(shuttles):
    print(f"Shuttle {i} has completed {shuttle.flights_completed} flights.")

Shuttle 0 has completed 0 flights.
Shuttle 1 has completed 0 flights.
Shuttle 2 has completed 5 flights.
Shuttle 3 has completed 10 flights.
Shuttle 4 has completed 10 flights.
Shuttle 5 has completed 4 flights.
Shuttle 6 has completed 2 flights.
Shuttle 7 has completed 2 flights.
Shuttle 8 has completed 6 flights.
Shuttle 9 has completed 9 flights.
Shuttle 10 has completed 9 flights.

In [15]:


for i, shuttle in enumerate(shuttles):
    distance = shuttles[0].get_distance(shuttle)
    print(f"The first shuttle is {distance:.2f} units away from shuttle {i}.")

The first shuttle is 0.00 units away from shuttle 0.
The first shuttle is 46.23 units away from shuttle 1.
The first shuttle is 23.54 units away from shuttle 2.
The first shuttle is 46.62 units away from shuttle 3.
The first shuttle is 61.27 units away from shuttle 4.
The first shuttle is 78.52 units away from shuttle 5.
The first shuttle is 29.07 units away from shuttle 6.
The first shuttle is 26.17 units away from shuttle 7.
The first shuttle is 33.94 units away from shuttle 8.
The first shuttle is 48.83 units away from shuttle 9.
The first shuttle is 55.80 units away from shuttle 10.

In [16]:

for i, rocket in enumerate(rockets):
    distance = shuttles[0].get_distance(rocket)
    print(f"The first shuttle is {distance:.2f} units away from rocket {i}.")

The first shuttle is 32.80 units away from rocket 0.
The first shuttle is 54.13 units away from rocket 1.
The first shuttle is 45.79 units away from rocket 2.
The first shuttle is 29.07 units away from rocket 3.
The first shuttle is 47.54 units away from rocket 4.
The first shuttle is 34.21 units away from rocket 5.
The first shuttle is 18.60 units away from rocket 6.
The first shuttle is 75.58 units away from rocket 7.
The first shuttle is 53.85 units away from rocket 8.
The first shuttle is 52.81 units away from rocket 9.
The first shuttle is 48.33 units away from rocket 10.