# HW2

In [4]:
import pandas as pd
import numpy as np

nba = pd.read_csv("../Data/Seasons_Stats_NBA.csv")
nba

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,0.368,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,0.435,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0
2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,0.394,...,0.698,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0
3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,0.312,...,0.559,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0
4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,0.308,...,0.548,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24686,2017.0,Cody Zeller,PF,24.0,CHO,62.0,58.0,1725.0,16.7,0.604,...,0.679,135.0,270.0,405.0,99.0,62.0,58.0,65.0,189.0,639.0
24687,2017.0,Tyler Zeller,C,27.0,BOS,51.0,5.0,525.0,13.0,0.508,...,0.564,43.0,81.0,124.0,42.0,7.0,21.0,20.0,61.0,178.0
24688,2017.0,Stephen Zimmerman,C,20.0,ORL,19.0,0.0,108.0,7.3,0.346,...,0.600,11.0,24.0,35.0,4.0,2.0,5.0,3.0,17.0,23.0
24689,2017.0,Paul Zipser,SF,22.0,CHI,44.0,18.0,843.0,6.9,0.503,...,0.775,15.0,110.0,125.0,36.0,15.0,16.0,40.0,78.0,240.0
24690,2017.0,Ivica Zubac,C,19.0,LAL,38.0,11.0,609.0,17.0,0.547,...,0.653,41.0,118.0,159.0,30.0,14.0,33.0,30.0,66.0,284.0

#### 1. Which NBA player scored the most points in a single season? What seasons/year was this? <a class="anchor" id="bullet1"></a>

In [5]:
q1 = (
    nba.loc[nba["PTS"] == nba["PTS"].max(), ["Player", "Year", "PTS"]]
       .drop_duplicates()
       .sort_values(["Player", "Year"])
       .reset_index(drop=True)
)

display(q1.head())
display(q1.tail())
q1

              Player    Year     PTS
0  Wilt Chamberlain*  1962.0  4029.0

              Player    Year     PTS
0  Wilt Chamberlain*  1962.0  4029.0

              Player    Year     PTS
0  Wilt Chamberlain*  1962.0  4029.0

In [6]:
q1["Year"] = q1["Year"].astype(int)
q1

              Player  Year     PTS
0  Wilt Chamberlain*  1962  4029.0

#### 2. Which NBA player scored the most points in 1991? <a class="anchor" id="bullet2"></a>

In 1991, Michael Jordan scored the most points.

In [7]:
q2_pool = nba.loc[nba["Year"] == 1991, ["Player", "Year", "PTS"]].copy()
q2_pool = q2_pool.dropna(subset=["PTS"])

q2 = (
    q2_pool.loc[q2_pool["PTS"] == q2_pool["PTS"].max()]
           .drop_duplicates()
           .sort_values(["Player"])
           .reset_index(drop=True)
)

q2["Year"] = q2["Year"].astype(int)

display(q2.head())
display(q2.tail())
q2

            Player  Year     PTS
0  Michael Jordan*  1991  2580.0

            Player  Year     PTS
0  Michael Jordan*  1991  2580.0

            Player  Year     PTS
0  Michael Jordan*  1991  2580.0

#### 3. Which player had the best free throw percentage ("FT%") from the year 2000 to the most recent year in the data? <a class="anchor" id="bullet3"></a>

There are many players who have a FT% of 100%, below is a list of these players sorted by their name (Player). Don't need to sort, but it is nice to see who had 100% FT% while shooting the most shots.

In [8]:
most_recent_year = int(nba["Year"].max())
q3_pool = nba.loc[(nba["Year"] >= 2000) & (nba["Year"] <= most_recent_year),
                  ["Player", "Year", "FT%"]].copy()

q3_pool = q3_pool.dropna(subset=["FT%","Player","Year"])

best_ft = q3_pool["FT%"].max()

q3 = (
    q3_pool.loc[q3_pool["FT%"] == best_ft, ["Player","Year","FT%"]]
           .drop_duplicates()
           .sort_values(["Player"]) 
           .reset_index(drop=True)
)

q3["Year"] = q3["Year"].astype(int)

display(q3.head())
display(q3.tail())
q3

            Player  Year  FT%
0      Aaron Miles  2006  1.0
1  Adam Harrington  2003  1.0
2    Adonis Thomas  2014  1.0
3   Adrian Griffin  2008  1.0
4        Alex Kirk  2015  1.0

              Player  Year  FT%
270    Wesley Person  2004  1.0
271     Will Blalock  2007  1.0
272      Yuta Tabuse  2005  1.0
273  Zarko Cabarkapa  2005  1.0
274  Zendon Hamilton  2003  1.0

              Player  Year  FT%
0        Aaron Miles  2006  1.0
1    Adam Harrington  2003  1.0
2      Adonis Thomas  2014  1.0
3     Adrian Griffin  2008  1.0
4          Alex Kirk  2015  1.0
..               ...   ...  ...
270    Wesley Person  2004  1.0
271     Will Blalock  2007  1.0
272      Yuta Tabuse  2005  1.0
273  Zarko Cabarkapa  2005  1.0
274  Zendon Hamilton  2003  1.0

[275 rows x 3 columns]

#### 4. Among those with at least 50 attempts ('FTA'), which player had the best free throw percentage ("FT%") from the year 2000 to the most recent year in the data? <a class="anchor" id="bullet4"></a>

Among those with at least 50 free throw attempts (FTA), Terrell Brandon had the best FT% since 2000.

In [9]:
most_recent_year = int(nba["Year"].max())
q4_pool = nba.loc[(nba["Year"] >= 2000) & (nba["Year"] <= most_recent_year) & (nba["FTA"] >= 50),
                  ["Player", "Year", "FTA", "FT%"]].copy()

q4_pool = q4_pool.dropna(subset=["FT%","Player","Year","FTA"])

best_ft_50 = q4_pool["FT%"].max()

q4 = (
    q4_pool.loc[q4_pool["FT%"] == best_ft_50, ["Player","Year","FTA","FT%"]]
           .drop_duplicates()
           .sort_values(["Player"])
           .reset_index(drop=True)
)

q4["Year"] = q4["Year"].astype(int)

display(q4.head())
display(q4.tail())
q4

            Player  Year   FTA    FT%
0  Terrell Brandon  2002  84.0  0.988

            Player  Year   FTA    FT%
0  Terrell Brandon  2002  84.0  0.988

            Player  Year   FTA    FT%
0  Terrell Brandon  2002  84.0  0.988

#### 5. Rename the variable "Pos" to "Position".

In [10]:
nba = nba.rename(columns={"Pos": "Position"})

display(nba[["Position"]].head())
display(nba[["Position"]].tail())

  Position
0      G-F
1       SG
2       SF
3        F
4        F

      Position
24686       PF
24687        C
24688        C
24689       SF
24690        C

#### 6. Use this variable to create two variables that are called "first_position" and "second_position".

In [11]:
pos_split = nba["Position"].astype("string").str.split("-", n=1, expand=True)
nba["first_position"] = pos_split[0]
nba["second_position"] = pos_split[1] 

display(nba[["Position", "first_position", "second_position"]].head())
display(nba[["Position", "first_position", "second_position"]].tail())

  Position first_position second_position
0      G-F              G               F
1       SG             SG            <NA>
2       SF             SF            <NA>
3        F              F            <NA>
4        F              F            <NA>

      Position first_position second_position
24686       PF             PF            <NA>
24687        C              C            <NA>
24688        C              C            <NA>
24689       SF             SF            <NA>
24690        C              C            <NA>

#### 7. Combine these two variables back into a single variable called "position_united".

In [12]:
nba["position_united"] = np.where(
    nba["second_position"].isna() | (nba["second_position"].astype("string").str.len() == 0),
    nba["first_position"].astype("string"),
    nba["first_position"].astype("string") + "-" + nba["second_position"].astype("string")
)

pos_freq = (
    nba["position_united"]
      .value_counts(dropna=False)
      .rename_axis("position_united")
      .reset_index(name="count")
)

display(pos_freq.head())
display(pos_freq.tail())
pos_freq

  position_united  count
0              PF   4966
1              SG   4811
2               C   4759
3              SF   4699
4              PG   4648

   position_united  count
19           SF-PF     21
20           SG-PF      3
21            C-SF      2
22           SF-PG      1
23           PG-SF      1

   position_united  count
0               PF   4966
1               SG   4811
2                C   4759
3               SF   4699
4               PG   4648
5                G    139
6                F    123
7              F-C     81
8              G-F     79
9             <NA>     67
10             F-G     60
11             C-F     35
12            C-PF     33
13           SF-SG     30
14           PG-SG     28
15           SG-PG     27
16            PF-C     27
17           SG-SF     26
18           PF-SF     25
19           SF-PF     21
20           SG-PF      3
21            C-SF      2
22           SF-PG      1
23           PG-SF      1

#### 8. Create two new datasets. <a class="anchor" id="bullet8"></a>

In [13]:
n = len(nba)
mergeid = pd.Series(range(1, n + 1), name="mergeid")

nba_no_age = nba.drop(columns=["Age"]).copy()
nba_no_age.insert(0, "mergeid", mergeid)  # put mergeid as first column

nba_year_player_age = nba[["Year", "Player", "Age"]].copy()
nba_year_player_age.insert(0, "mergeid", mergeid)

display(nba_no_age.head())
display(nba_no_age.tail())

display(nba_year_player_age.head())
display(nba_year_player_age.tail())

,mergeid,Year,Player,Position,Tm,G,GS,MP,PER,TS%,...,TRB,AST,STL,BLK,TOV,PF,PTS,first_position,second_position,position_united
0,1,1950.0,Curly Armstrong,G-F,FTW,63.0,NaN,NaN,NaN,0.368,...,NaN,176.0,NaN,NaN,NaN,217.0,458.0,G,F,G-F
1,2,1950.0,Cliff Barker,SG,INO,49.0,NaN,NaN,NaN,0.435,...,NaN,109.0,NaN,NaN,NaN,99.0,279.0,SG,<NA>,SG
2,3,1950.0,Leo Barnhorst,SF,CHS,67.0,NaN,NaN,NaN,0.394,...,NaN,140.0,NaN,NaN,NaN,192.0,438.0,SF,<NA>,SF
3,4,1950.0,Ed Bartels,F,TOT,15.0,NaN,NaN,NaN,0.312,...,NaN,20.0,NaN,NaN,NaN,29.0,63.0,F,<NA>,F
4,5,1950.0,Ed Bartels,F,DNN,13.0,NaN,NaN,NaN,0.308,...,NaN,20.0,NaN,NaN,NaN,27.0,59.0,F,<NA>,F

,mergeid,Year,Player,Position,Tm,G,GS,MP,PER,TS%,...,TRB,AST,STL,BLK,TOV,PF,PTS,first_position,second_position,position_united
24686,24687,2017.0,Cody Zeller,PF,CHO,62.0,58.0,1725.0,16.7,0.604,...,405.0,99.0,62.0,58.0,65.0,189.0,639.0,PF,<NA>,PF
24687,24688,2017.0,Tyler Zeller,C,BOS,51.0,5.0,525.0,13.0,0.508,...,124.0,42.0,7.0,21.0,20.0,61.0,178.0,C,<NA>,C
24688,24689,2017.0,Stephen Zimmerman,C,ORL,19.0,0.0,108.0,7.3,0.346,...,35.0,4.0,2.0,5.0,3.0,17.0,23.0,C,<NA>,C
24689,24690,2017.0,Paul Zipser,SF,CHI,44.0,18.0,843.0,6.9,0.503,...,125.0,36.0,15.0,16.0,40.0,78.0,240.0,SF,<NA>,SF
24690,24691,2017.0,Ivica Zubac,C,LAL,38.0,11.0,609.0,17.0,0.547,...,159.0,30.0,14.0,33.0,30.0,66.0,284.0,C,<NA>,C

   mergeid    Year           Player   Age
0        1  1950.0  Curly Armstrong  31.0
1        2  1950.0     Cliff Barker  29.0
2        3  1950.0    Leo Barnhorst  25.0
3        4  1950.0       Ed Bartels  24.0
4        5  1950.0       Ed Bartels  24.0

       mergeid    Year             Player   Age
24686    24687  2017.0        Cody Zeller  24.0
24687    24688  2017.0       Tyler Zeller  27.0
24688    24689  2017.0  Stephen Zimmerman  20.0
24689    24690  2017.0        Paul Zipser  22.0
24690    24691  2017.0        Ivica Zubac  19.0

#### 9. Join the two datasets from question (8) together to recreate the original dataset plus the new merge id. <a class="anchor" id="bullet9"></a>

In [14]:
nba_recreated = (
    nba_no_age.merge(nba_year_player_age, on="mergeid", how="inner")
)

print("original rows:", nba.shape[0], "recreated rows:", nba_recreated.shape[0])
print("has mergeid:", "mergeid" in nba_recreated.columns)

display(nba_recreated.head())
display(nba_recreated.tail())

original rows: 24691 recreated rows: 24691
has mergeid: True

,mergeid,Year_x,Player_x,Position,Tm,G,GS,MP,PER,TS%,...,BLK,TOV,PF,PTS,first_position,second_position,position_united,Year_y,Player_y,Age
0,1,1950.0,Curly Armstrong,G-F,FTW,63.0,NaN,NaN,NaN,0.368,...,NaN,NaN,217.0,458.0,G,F,G-F,1950.0,Curly Armstrong,31.0
1,2,1950.0,Cliff Barker,SG,INO,49.0,NaN,NaN,NaN,0.435,...,NaN,NaN,99.0,279.0,SG,<NA>,SG,1950.0,Cliff Barker,29.0
2,3,1950.0,Leo Barnhorst,SF,CHS,67.0,NaN,NaN,NaN,0.394,...,NaN,NaN,192.0,438.0,SF,<NA>,SF,1950.0,Leo Barnhorst,25.0
3,4,1950.0,Ed Bartels,F,TOT,15.0,NaN,NaN,NaN,0.312,...,NaN,NaN,29.0,63.0,F,<NA>,F,1950.0,Ed Bartels,24.0
4,5,1950.0,Ed Bartels,F,DNN,13.0,NaN,NaN,NaN,0.308,...,NaN,NaN,27.0,59.0,F,<NA>,F,1950.0,Ed Bartels,24.0

,mergeid,Year_x,Player_x,Position,Tm,G,GS,MP,PER,TS%,...,BLK,TOV,PF,PTS,first_position,second_position,position_united,Year_y,Player_y,Age
24686,24687,2017.0,Cody Zeller,PF,CHO,62.0,58.0,1725.0,16.7,0.604,...,58.0,65.0,189.0,639.0,PF,<NA>,PF,2017.0,Cody Zeller,24.0
24687,24688,2017.0,Tyler Zeller,C,BOS,51.0,5.0,525.0,13.0,0.508,...,21.0,20.0,61.0,178.0,C,<NA>,C,2017.0,Tyler Zeller,27.0
24688,24689,2017.0,Stephen Zimmerman,C,ORL,19.0,0.0,108.0,7.3,0.346,...,5.0,3.0,17.0,23.0,C,<NA>,C,2017.0,Stephen Zimmerman,20.0
24689,24690,2017.0,Paul Zipser,SF,CHI,44.0,18.0,843.0,6.9,0.503,...,16.0,40.0,78.0,240.0,SF,<NA>,SF,2017.0,Paul Zipser,22.0
24690,24691,2017.0,Ivica Zubac,C,LAL,38.0,11.0,609.0,17.0,0.547,...,33.0,30.0,66.0,284.0,C,<NA>,C,2017.0,Ivica Zubac,19.0

In [15]:
nba_recreated_clean = nba_recreated.copy()

nba_recreated_clean = nba_recreated_clean.drop(columns=["Year_y", "Player_y"], errors="ignore")
nba_recreated_clean = nba_recreated_clean.rename(columns={"Year_x": "Year", "Player_x": "Player"})

display(nba_recreated_clean.head())
display(nba_recreated_clean.tail())

,mergeid,Year,Player,Position,Tm,G,GS,MP,PER,TS%,...,AST,STL,BLK,TOV,PF,PTS,first_position,second_position,position_united,Age
0,1,1950.0,Curly Armstrong,G-F,FTW,63.0,NaN,NaN,NaN,0.368,...,176.0,NaN,NaN,NaN,217.0,458.0,G,F,G-F,31.0
1,2,1950.0,Cliff Barker,SG,INO,49.0,NaN,NaN,NaN,0.435,...,109.0,NaN,NaN,NaN,99.0,279.0,SG,<NA>,SG,29.0
2,3,1950.0,Leo Barnhorst,SF,CHS,67.0,NaN,NaN,NaN,0.394,...,140.0,NaN,NaN,NaN,192.0,438.0,SF,<NA>,SF,25.0
3,4,1950.0,Ed Bartels,F,TOT,15.0,NaN,NaN,NaN,0.312,...,20.0,NaN,NaN,NaN,29.0,63.0,F,<NA>,F,24.0
4,5,1950.0,Ed Bartels,F,DNN,13.0,NaN,NaN,NaN,0.308,...,20.0,NaN,NaN,NaN,27.0,59.0,F,<NA>,F,24.0

,mergeid,Year,Player,Position,Tm,G,GS,MP,PER,TS%,...,AST,STL,BLK,TOV,PF,PTS,first_position,second_position,position_united,Age
24686,24687,2017.0,Cody Zeller,PF,CHO,62.0,58.0,1725.0,16.7,0.604,...,99.0,62.0,58.0,65.0,189.0,639.0,PF,<NA>,PF,24.0
24687,24688,2017.0,Tyler Zeller,C,BOS,51.0,5.0,525.0,13.0,0.508,...,42.0,7.0,21.0,20.0,61.0,178.0,C,<NA>,C,27.0
24688,24689,2017.0,Stephen Zimmerman,C,ORL,19.0,0.0,108.0,7.3,0.346,...,4.0,2.0,5.0,3.0,17.0,23.0,C,<NA>,C,20.0
24689,24690,2017.0,Paul Zipser,SF,CHI,44.0,18.0,843.0,6.9,0.503,...,36.0,15.0,16.0,40.0,78.0,240.0,SF,<NA>,SF,22.0
24690,24691,2017.0,Ivica Zubac,C,LAL,38.0,11.0,609.0,17.0,0.547,...,30.0,14.0,33.0,30.0,66.0,284.0,C,<NA>,C,19.0

#### 10. Subset the original dataset to the years 1995-1997. Group the data by team name and year then summarize the average number of points per team. Arrange from most to least points. <a class="anchor" id="bullet10"></a>

In [16]:
q10 = (
    nba.loc[nba["Year"].between(1995, 1997), ["Tm", "Year", "PTS"]]
       .dropna(subset=["Tm", "Year", "PTS"])
       .groupby(["Tm", "Year"], as_index=False)
       .agg(avg_points=("PTS", "mean"))
       .sort_values("avg_points", ascending=False)
       .reset_index(drop=True)
)

q10["Year"] = q10["Year"].astype(int)

q10.shape
display(q10.head())
display(q10.tail())
q10

    Tm  Year  avg_points
0  SEA  1996  659.384615
1  SEA  1995  646.785714
2  MIN  1997  606.307692
3  ORL  1995  606.066667
4  PHO  1995  604.866667

     Tm  Year  avg_points
83  DEN  1997  348.695652
84  NJN  1997  346.695652
85  PHI  1996  322.750000
86  TOT  1997  322.380952
87  DAL  1997  275.222222

     Tm  Year  avg_points
0   SEA  1996  659.384615
1   SEA  1995  646.785714
2   MIN  1997  606.307692
3   ORL  1995  606.066667
4   PHO  1995  604.866667
..  ...   ...         ...
83  DEN  1997  348.695652
84  NJN  1997  346.695652
85  PHI  1996  322.750000
86  TOT  1997  322.380952
87  DAL  1997  275.222222

[88 rows x 3 columns]

#### 11. Similar to Q10, start by subsetting the original dataset to the years 1995-1997. Then create a wide dataset that keeps each year in its own row, but spreads team names to multiple columns with each column delineating points per team in each of the 1995-1997 seasons (Hint: Your final answer should have a shape of 3 x 30).  <a class="anchor" id="bullet11"></a>

In [17]:
q11 = (
    q10.pivot(index="Year", columns="Tm", values="avg_points")
       .reset_index()
)

q11.shape
display(q11.head())
display(q11.tail())
q11

Tm,Year,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,...,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
0,1995,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,...,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1,1996,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,...,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
2,1997,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,...,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

Tm,Year,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,...,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
0,1995,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,...,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1,1996,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,...,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
2,1997,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,...,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

Tm,Year,ATL,BOS,CHH,CHI,CLE,DAL,DEN,DET,GSW,...,PHO,POR,SAC,SAS,SEA,TOR,TOT,UTA,VAN,WSB
0,1995,440.055556,495.764706,515.562500,520.312500,494.466667,604.428571,488.764706,503.312500,481.500000,...,604.866667,528.187500,537.066667,546.375000,646.785714,NaN,488.681818,581.733333,NaN,515.125000
1,1996,447.722222,471.944444,401.476190,575.000000,498.200000,560.600000,471.352941,558.714286,490.235294,...,503.058824,543.000000,510.187500,565.133333,659.384615,420.736842,419.767857,600.285714,409.0000,400.380952
2,1997,457.294118,458.222222,450.444444,563.866667,551.769231,275.222222,348.695652,482.687500,510.687500,...,366.565217,427.052632,494.250000,370.900000,517.125000,372.809524,322.380952,563.600000,457.0625,543.133333

#### 12. Now return the data from #11 back into a long (tidy) format by moving Tm, Points and Year into their own columns. <a class="anchor" id="bullet12"></a>

In [19]:
q12 = (
    q11.melt(id_vars="Year", var_name="Tm", value_name="avg_points")
)

q12.shape
display(q12.head())
display(q12.tail())
q12

   Year   Tm  avg_points
0  1995  ATL  440.055556
1  1996  ATL  447.722222
2  1997  ATL  457.294118
3  1995  BOS  495.764706
4  1996  BOS  471.944444

    Year   Tm  avg_points
85  1996  VAN  409.000000
86  1997  VAN  457.062500
87  1995  WSB  515.125000
88  1996  WSB  400.380952
89  1997  WSB  543.133333

    Year   Tm  avg_points
0   1995  ATL  440.055556
1   1996  ATL  447.722222
2   1997  ATL  457.294118
3   1995  BOS  495.764706
4   1996  BOS  471.944444
..   ...  ...         ...
85  1996  VAN  409.000000
86  1997  VAN  457.062500
87  1995  WSB  515.125000
88  1996  WSB  400.380952
89  1997  WSB  543.133333

[90 rows x 3 columns]