# Max Chelminski
## HW4 Functions II

In [1]:
import pandas as pd
import numpy as np

1. **Import the data as a pd.DataFrame object. Use one or more functions from the pandas library to split the data into three unique datasets. The first should include columns that are factors only (i.e., categorical data), the second should include columns that are numeric only, and the third should include columns with logical/boolean variables only.**

In [2]:
houses = pd.read_csv('../../Data/Housing_prices_data.csv')
houses.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
houses_factors = houses.select_dtypes(include=object)
houses_factors.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [4]:
houses_numeric = houses.select_dtypes(include=[int, float])
houses_numeric.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [5]:
houses_boolean = houses.select_dtypes(include=bool)
houses_boolean.head()

   CentralAir
0        True
1        True
2        True
3        True
4        True

2. **Using the second dataset from question #1, for each numeric variable use the apply function from the pandas library to return the mean, median and standard deviation (SD) of all numeric variables.**

In [6]:
houses_numeric.apply([np.mean, np.median, np.std])

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
median,730.500000,50.000000,NaN,9478.500000,6.000000,5.000000,1973.000000,1994.000000,NaN,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
std,421.465598,42.286082,24.274639,9977.846105,1.382523,1.112418,30.192559,20.638335,181.003845,455.941866,...,125.295863,66.233333,61.098214,29.307289,55.738317,40.163545,495.953090,2.702700,1.327640,79415.291886

3. **Using the second dataset from question #1, create a new dataset that only includes the variable indicating sales price ("SalePrice"). Search for a categorical variable which has between 2-4 categories in the full dataset that you think may be related to the sales price of houses. Give the mean, median and SD for SalePrice based on the different groups of the categorical variables. Does the average price seem to vary by the different levels of the categorical factor you chose?**

In [7]:
houses_q3 = houses_numeric['SalePrice'].reset_index()
houses_q3['Street'] = houses_factors['Street']
houses_q3 = houses_q3.drop(columns='index')

In [8]:
houses_q3.groupby('Street').agg(['mean', 'median', 'std'])

            SalePrice
                 mean    median           std
Street
Grvl    130190.500000  114250.0  65446.253991
Pave    181130.538514  163000.0  79446.597317

It looks like the average sale price varies significantly depending on whether the Street is gravel or paved. The paved street houses are much more expensive on average, have a higher median, and vary a bit more, which is to be expected.

4. **Regress "SalePrice" on "LotArea", "OverallQual", "OverallCond" with the `statsmodels` library. Use the syntax below to replicate the output shown you are able to estimate this regression model.**

In [9]:
import statsmodels.api as sm

In [10]:
x = houses_numeric[['LotArea', 'OverallQual', 'OverallCond']]
y = houses_numeric['SalePrice']
x = sm.add_constant(x)

model = sm.OLS(y, x).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.659
Model:                            OLS   Adj. R-squared:                  0.658
Method:                 Least Squares   F-statistic:                     935.9
Date:                Wed, 25 Mar 2026   Prob (F-statistic):               0.00
Time:                        16:38:13   Log-Likelihood:                -17760.
No. Observations:                1460   AIC:                         3.553e+04
Df Residuals:                    1456   BIC:                         3.555e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.022e+05   8633.073    -11.832      0.000   -1.19e+05   -8.52e+04
LotArea         1.4503      0.123     11.831      0.000       1.210       1.691
OverallQual   4.43e+04    888.434     49.860      0.000    4.26e+04     4.6e+04
OverallCond  -423.6737   1097.973     -0.386      0.700   -2577.451    1730.104
==============================================================================
Omnibus:                      574.483   Durbin-Watson:                   1.966
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7330.883
Skew:                           1.468   Prob(JB):                         0.00
Kurtosis:                      13.578   Cond. No.                     1.04e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

5. **Write a for loop that loops through each level of the categorical factor you chose in Q3, where each iteration of the for loop subsets your data for one group of the categorical variable at a time, and then fits the same regression model specified above in Q4 k times, where k refers to the number of unique categories. On each iteration of your for loop, store the model.summary() information as a new element in a list object. Once your for loop is done running, print the list. There should be k regressions which you estimated. Does the effect of LotArea on SalePrice vary within the different levels of the categorical factor you chose? What is another, more common way to answer a question like this (i.e., a question about moderation or effect heterogeneity)?** *Hint: Don't forget to account for the standard error when comparing the regression slopes!*

In [11]:
houses_q5 = houses[['LotArea', 'OverallQual', 'OverallCond', 'SalePrice', 'Street']]

summary_list = []
for category in houses_q5['Street'].unique():
    houses_q5_cat = houses_q5[houses_q5['Street'] == category]
    x = houses_q5_cat[['LotArea', 'OverallQual', 'OverallCond']]
    y = houses_q5_cat['SalePrice']
    x = sm.add_constant(x)

    model = sm.OLS(y, x).fit()

    summary_list.append(model.summary())
    print(category)
print(summary_list)

Pave
Grvl
[<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.660
Model:                            OLS   Adj. R-squared:                  0.660
Method:                 Least Squares   F-statistic:                     939.7
Date:                Wed, 25 Mar 2026   Prob (F-statistic):               0.00
Time:                        16:38:13   Log-Likelihood:                -17683.
No. Observations:                1454   AIC:                         3.537e+04
Df Residuals:                    1450   BIC:                         3.539e+04
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const       -1.025e+05   8649.646    -11.854      0.000   -1.19e+05   -8.56e+04
LotArea         1.6096      0.134     11.976      0.000       1.346       1.873
OverallQual  4.411e+04    891.052     49.502      0.000    4.24e+04    4.59e+04
OverallCond  -417.6629   1097.321     -0.381      0.704   -2570.169    1734.844
==============================================================================
Omnibus:                      567.998   Durbin-Watson:                   1.957
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7588.277
Skew:                           1.439   Prob(JB):                         0.00
Kurtosis:                      13.815   Cond. No.                     9.91e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.91e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
""", <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.929
Model:                            OLS   Adj. R-squared:                  0.822
Method:                 Least Squares   F-statistic:                     8.687
Date:                Wed, 25 Mar 2026   Prob (F-statistic):              0.105
Time:                        16:38:13   Log-Likelihood:                -66.577
No. Observations:                   6   AIC:                             141.2
Df Residuals:                       2   BIC:                             140.3
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        2.117e+05   9.94e+04      2.129      0.167   -2.16e+05     6.4e+05
LotArea         1.3832      0.295      4.682      0.043       0.112       2.654
OverallQual  3.857e+04   1.59e+04      2.424      0.136   -2.99e+04    1.07e+05
OverallCond -6.721e+04   2.77e+04     -2.430      0.136   -1.86e+05    5.18e+04
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.187
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.219
Skew:                           0.468   Prob(JB):                        0.896
Kurtosis:                       2.962   Cond. No.                     6.27e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.27e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""]

C:\Users\Max\anaconda3\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "

There appears to be some slight variation of the effect of LotArea on SalePrice dependent on the type of Street.  
  
When the Street is paved, every additional unit of LotArea adds 1.61 to the SalePrice,  
  
while when the Street is gravel, every additional unit of LotArea adds 1.38 to the SalePrice.  
  
However, these values are within the standard errors for each other, so the actual effect may not be significant.  
  
The more common way to answer questions about effect heterogeneity involves fitting the regression model with an interaction term between LotArea and Street by multiplying them together.

6. **Using the first dataset from question #1, for each categorical variable use a for loop to print a frequency and relative frequency table for every variable. To make your output readable, for each variable you should print the following in this order, placing the variable name where you see blanks below.**

In [12]:
for variable in houses_factors:
    frequency = houses_factors[variable].value_counts()
    relative_frequency = houses_factors[variable].value_counts(normalize=True)
    print(f"Frequency table for {variable} ============\n{frequency}\n\nRelative frequency table for {variable} ============\n{relative_frequency}\n\n")

Frequency table for MSZoning ============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative frequency table for MSZoning ============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64


Frequency table for Street ============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative frequency table for Street ============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64


Frequency table for Alley ============
Alley
Grvl    50
Pave    41
Name: count, dtype: int64

Relative frequency table for Alley ============
Alley
Grvl    0.549451
Pave    0.450549
Name: proportion, dtype: float64


Frequency table for LotShape ============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative frequency table for LotShape ============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64


Frequency table for LandContour ============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative frequency table for LandContour ============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64


Frequency table for Utilities ============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative frequency table for Utilities ============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64


Frequency table for LotConfig ============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative frequency table for LotConfig ============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64


Frequency table for LandSlope ============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative frequency table for LandSlope ============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64


Frequency table for Neighborhood ============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative frequency table for Neighborhood ============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
SWISU      0.017123
StoneBr    0.017123
Blmngtn    0.011644
MeadowV    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64


Frequency table for Condition1 ============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative frequency table for Condition1 ============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64


Frequency table for Condition2 ============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative frequency table for Condition2 ============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64


Frequency table for BldgType ============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative frequency table for BldgType ============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64


Frequency table for HouseStyle ============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative frequency table for HouseStyle ============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64


Frequency table for RoofStyle ============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative frequency table for RoofStyle ============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64


Frequency table for RoofMatl ============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative frequency table for RoofMatl ============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64


Frequency table for Exterior1st ============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior1st ============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64


Frequency table for Exterior2nd ============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior2nd ============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64


Frequency table for MasVnrType ============
MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative frequency table for MasVnrType ============
MasVnrType
BrkFace    0.756803
Stone      0.217687
BrkCmn     0.025510
Name: proportion, dtype: float64


Frequency table for ExterQual ============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative frequency table for ExterQual ============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64


Frequency table for ExterCond ============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative frequency table for ExterCond ============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64


Frequency table for Foundation ============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative frequency table for Foundation ============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64


Frequency table for BsmtQual ============
BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

Relative frequency table for BsmtQual ============
BsmtQual
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: proportion, dtype: float64


Frequency table for BsmtCond ============
BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

Relative frequency table for BsmtCond ============
BsmtCond
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: proportion, dtype: float64


Frequency table for BsmtExposure ============
BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

Relative frequency table for BsmtExposure ============
BsmtExposure
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: proportion, dtype: float64


Frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

Relative frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: proportion, dtype: float64


Frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: proportion, dtype: float64


Frequency table for Heating ============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative frequency table for Heating ============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64


Frequency table for HeatingQC ============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative frequency table for HeatingQC ============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64


Frequency table for Electrical ============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

Relative frequency table for Electrical ============
Electrical
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: proportion, dtype: float64


Frequency table for KitchenQual ============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative frequency table for KitchenQual ============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64


Frequency table for Functional ============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative frequency table for Functional ============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64


Frequency table for FireplaceQu ============
FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

Relative frequency table for FireplaceQu ============
FireplaceQu
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: proportion, dtype: float64


Frequency table for GarageType ============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative frequency table for GarageType ============
GarageType
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: proportion, dtype: float64


Frequency table for GarageFinish ============
GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

Relative frequency table for GarageFinish ============
GarageFinish
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: proportion, dtype: float64


Frequency table for GarageQual ============
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

Relative frequency table for GarageQual ============
GarageQual
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: proportion, dtype: float64


Frequency table for GarageCond ============
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

Relative frequency table for GarageCond ============
GarageCond
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: proportion, dtype: float64


Frequency table for PavedDrive ============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative frequency table for PavedDrive ============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64


Frequency table for PoolQC ============
PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

Relative frequency table for PoolQC ============
PoolQC
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: proportion, dtype: float64


Frequency table for Fence ============
Fence
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: count, dtype: int64

Relative frequency table for Fence ============
Fence
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: proportion, dtype: float64


Frequency table for MiscFeature ============
MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

Relative frequency table for MiscFeature ============
MiscFeature
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: proportion, dtype: float64


Frequency table for SaleType ============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative frequency table for SaleType ============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64


Frequency table for SaleCondition ============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative frequency table for SaleCondition ============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

7. **Do the same thing as number 6, but with a while loop this time.**

In [13]:
i = 0
while i < len(houses_factors.columns):
    frequency = houses_factors[houses_factors.columns[i]].value_counts()
    relative_frequency = houses_factors[houses_factors.columns[i]].value_counts(normalize=True)
    print(f"Frequency table for {houses_factors.columns[i]} ============\n{frequency}\n\nRelative frequency table for {houses_factors.columns[i]} ============\n{relative_frequency}\n\n")
    i += 1

Frequency table for MSZoning ============
MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64

Relative frequency table for MSZoning ============
MSZoning
RL         0.788356
RM         0.149315
FV         0.044521
RH         0.010959
C (all)    0.006849
Name: proportion, dtype: float64


Frequency table for Street ============
Street
Pave    1454
Grvl       6
Name: count, dtype: int64

Relative frequency table for Street ============
Street
Pave    0.99589
Grvl    0.00411
Name: proportion, dtype: float64


Frequency table for Alley ============
Alley
Grvl    50
Pave    41
Name: count, dtype: int64

Relative frequency table for Alley ============
Alley
Grvl    0.549451
Pave    0.450549
Name: proportion, dtype: float64


Frequency table for LotShape ============
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Relative frequency table for LotShape ============
LotShape
Reg    0.633562
IR1    0.331507
IR2    0.028082
IR3    0.006849
Name: proportion, dtype: float64


Frequency table for LandContour ============
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64

Relative frequency table for LandContour ============
LandContour
Lvl    0.897945
Bnk    0.043151
HLS    0.034247
Low    0.024658
Name: proportion, dtype: float64


Frequency table for Utilities ============
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64

Relative frequency table for Utilities ============
Utilities
AllPub    0.999315
NoSeWa    0.000685
Name: proportion, dtype: float64


Frequency table for LotConfig ============
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64

Relative frequency table for LotConfig ============
LotConfig
Inside     0.720548
Corner     0.180137
CulDSac    0.064384
FR2        0.032192
FR3        0.002740
Name: proportion, dtype: float64


Frequency table for LandSlope ============
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64

Relative frequency table for LandSlope ============
LandSlope
Gtl    0.946575
Mod    0.044521
Sev    0.008904
Name: proportion, dtype: float64


Frequency table for Neighborhood ============
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
SWISU       25
StoneBr     25
Blmngtn     17
MeadowV     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64

Relative frequency table for Neighborhood ============
Neighborhood
NAmes      0.154110
CollgCr    0.102740
OldTown    0.077397
Edwards    0.068493
Somerst    0.058904
Gilbert    0.054110
NridgHt    0.052740
Sawyer     0.050685
NWAmes     0.050000
SawyerW    0.040411
BrkSide    0.039726
Crawfor    0.034932
Mitchel    0.033562
NoRidge    0.028082
Timber     0.026027
IDOTRR     0.025342
ClearCr    0.019178
SWISU      0.017123
StoneBr    0.017123
Blmngtn    0.011644
MeadowV    0.011644
BrDale     0.010959
Veenker    0.007534
NPkVill    0.006164
Blueste    0.001370
Name: proportion, dtype: float64


Frequency table for Condition1 ============
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64

Relative frequency table for Condition1 ============
Condition1
Norm      0.863014
Feedr     0.055479
Artery    0.032877
RRAn      0.017808
PosN      0.013014
RRAe      0.007534
PosA      0.005479
RRNn      0.003425
RRNe      0.001370
Name: proportion, dtype: float64


Frequency table for Condition2 ============
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64

Relative frequency table for Condition2 ============
Condition2
Norm      0.989726
Feedr     0.004110
Artery    0.001370
RRNn      0.001370
PosN      0.001370
PosA      0.000685
RRAn      0.000685
RRAe      0.000685
Name: proportion, dtype: float64


Frequency table for BldgType ============
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64

Relative frequency table for BldgType ============
BldgType
1Fam      0.835616
TwnhsE    0.078082
Duplex    0.035616
Twnhs     0.029452
2fmCon    0.021233
Name: proportion, dtype: float64


Frequency table for HouseStyle ============
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64

Relative frequency table for HouseStyle ============
HouseStyle
1Story    0.497260
2Story    0.304795
1.5Fin    0.105479
SLvl      0.044521
SFoyer    0.025342
1.5Unf    0.009589
2.5Unf    0.007534
2.5Fin    0.005479
Name: proportion, dtype: float64


Frequency table for RoofStyle ============
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64

Relative frequency table for RoofStyle ============
RoofStyle
Gable      0.781507
Hip        0.195890
Flat       0.008904
Gambrel    0.007534
Mansard    0.004795
Shed       0.001370
Name: proportion, dtype: float64


Frequency table for RoofMatl ============
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64

Relative frequency table for RoofMatl ============
RoofMatl
CompShg    0.982192
Tar&Grv    0.007534
WdShngl    0.004110
WdShake    0.003425
Metal      0.000685
Membran    0.000685
Roll       0.000685
ClyTile    0.000685
Name: proportion, dtype: float64


Frequency table for Exterior1st ============
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior1st ============
Exterior1st
VinylSd    0.352740
HdBoard    0.152055
MetalSd    0.150685
Wd Sdng    0.141096
Plywood    0.073973
CemntBd    0.041781
BrkFace    0.034247
WdShing    0.017808
Stucco     0.017123
AsbShng    0.013699
BrkComm    0.001370
Stone      0.001370
AsphShn    0.000685
ImStucc    0.000685
CBlock     0.000685
Name: proportion, dtype: float64


Frequency table for Exterior2nd ============
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64

Relative frequency table for Exterior2nd ============
Exterior2nd
VinylSd    0.345205
MetalSd    0.146575
HdBoard    0.141781
Wd Sdng    0.134932
Plywood    0.097260
CmentBd    0.041096
Wd Shng    0.026027
Stucco     0.017808
BrkFace    0.017123
AsbShng    0.013699
ImStucc    0.006849
Brk Cmn    0.004795
Stone      0.003425
AsphShn    0.002055
Other      0.000685
CBlock     0.000685
Name: proportion, dtype: float64


Frequency table for MasVnrType ============
MasVnrType
BrkFace    445
Stone      128
BrkCmn      15
Name: count, dtype: int64

Relative frequency table for MasVnrType ============
MasVnrType
BrkFace    0.756803
Stone      0.217687
BrkCmn     0.025510
Name: proportion, dtype: float64


Frequency table for ExterQual ============
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64

Relative frequency table for ExterQual ============
ExterQual
TA    0.620548
Gd    0.334247
Ex    0.035616
Fa    0.009589
Name: proportion, dtype: float64


Frequency table for ExterCond ============
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64

Relative frequency table for ExterCond ============
ExterCond
TA    0.878082
Gd    0.100000
Fa    0.019178
Ex    0.002055
Po    0.000685
Name: proportion, dtype: float64


Frequency table for Foundation ============
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64

Relative frequency table for Foundation ============
Foundation
PConc     0.443151
CBlock    0.434247
BrkTil    0.100000
Slab      0.016438
Stone     0.004110
Wood      0.002055
Name: proportion, dtype: float64


Frequency table for BsmtQual ============
BsmtQual
TA    649
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64

Relative frequency table for BsmtQual ============
BsmtQual
TA    0.456079
Gd    0.434294
Ex    0.085032
Fa    0.024596
Name: proportion, dtype: float64


Frequency table for BsmtCond ============
BsmtCond
TA    1311
Gd      65
Fa      45
Po       2
Name: count, dtype: int64

Relative frequency table for BsmtCond ============
BsmtCond
TA    0.921293
Gd    0.045678
Fa    0.031623
Po    0.001405
Name: proportion, dtype: float64


Frequency table for BsmtExposure ============
BsmtExposure
No    953
Av    221
Gd    134
Mn    114
Name: count, dtype: int64

Relative frequency table for BsmtExposure ============
BsmtExposure
No    0.670183
Av    0.155415
Gd    0.094233
Mn    0.080169
Name: proportion, dtype: float64


Frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64

Relative frequency table for BsmtFinType1 ============
BsmtFinType1
Unf    0.302178
GLQ    0.293746
ALQ    0.154603
BLQ    0.104006
Rec    0.093465
LwQ    0.052003
Name: proportion, dtype: float64


Frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64

Relative frequency table for BsmtFinType2 ============
BsmtFinType2
Unf    0.883263
Rec    0.037975
LwQ    0.032349
BLQ    0.023207
ALQ    0.013361
GLQ    0.009845
Name: proportion, dtype: float64


Frequency table for Heating ============
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64

Relative frequency table for Heating ============
Heating
GasA     0.978082
GasW     0.012329
Grav     0.004795
Wall     0.002740
OthW     0.001370
Floor    0.000685
Name: proportion, dtype: float64


Frequency table for HeatingQC ============
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64

Relative frequency table for HeatingQC ============
HeatingQC
Ex    0.507534
TA    0.293151
Gd    0.165068
Fa    0.033562
Po    0.000685
Name: proportion, dtype: float64


Frequency table for Electrical ============
Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

Relative frequency table for Electrical ============
Electrical
SBrkr    0.914325
FuseA    0.064428
FuseF    0.018506
FuseP    0.002056
Mix      0.000685
Name: proportion, dtype: float64


Frequency table for KitchenQual ============
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64

Relative frequency table for KitchenQual ============
KitchenQual
TA    0.503425
Gd    0.401370
Ex    0.068493
Fa    0.026712
Name: proportion, dtype: float64


Frequency table for Functional ============
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64

Relative frequency table for Functional ============
Functional
Typ     0.931507
Min2    0.023288
Min1    0.021233
Mod     0.010274
Maj1    0.009589
Maj2    0.003425
Sev     0.000685
Name: proportion, dtype: float64


Frequency table for FireplaceQu ============
FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

Relative frequency table for FireplaceQu ============
FireplaceQu
Gd    0.493506
TA    0.406494
Fa    0.042857
Ex    0.031169
Po    0.025974
Name: proportion, dtype: float64


Frequency table for GarageType ============
GarageType
Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64

Relative frequency table for GarageType ============
GarageType
Attchd     0.630892
Detchd     0.280638
BuiltIn    0.063814
Basment    0.013778
CarPort    0.006526
2Types     0.004351
Name: proportion, dtype: float64


Frequency table for GarageFinish ============
GarageFinish
Unf    605
RFn    422
Fin    352
Name: count, dtype: int64

Relative frequency table for GarageFinish ============
GarageFinish
Unf    0.438724
RFn    0.306019
Fin    0.255257
Name: proportion, dtype: float64


Frequency table for GarageQual ============
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

Relative frequency table for GarageQual ============
GarageQual
TA    0.950689
Fa    0.034808
Gd    0.010152
Ex    0.002175
Po    0.002175
Name: proportion, dtype: float64


Frequency table for GarageCond ============
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64

Relative frequency table for GarageCond ============
GarageCond
TA    0.961566
Fa    0.025381
Gd    0.006526
Po    0.005076
Ex    0.001450
Name: proportion, dtype: float64


Frequency table for PavedDrive ============
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64

Relative frequency table for PavedDrive ============
PavedDrive
Y    0.917808
N    0.061644
P    0.020548
Name: proportion, dtype: float64


Frequency table for PoolQC ============
PoolQC
Gd    3
Ex    2
Fa    2
Name: count, dtype: int64

Relative frequency table for PoolQC ============
PoolQC
Gd    0.428571
Ex    0.285714
Fa    0.285714
Name: proportion, dtype: float64


Frequency table for Fence ============
Fence
MnPrv    157
GdPrv     59
GdWo      54
MnWw      11
Name: count, dtype: int64

Relative frequency table for Fence ============
Fence
MnPrv    0.558719
GdPrv    0.209964
GdWo     0.192171
MnWw     0.039146
Name: proportion, dtype: float64


Frequency table for MiscFeature ============
MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

Relative frequency table for MiscFeature ============
MiscFeature
Shed    0.907407
Gar2    0.037037
Othr    0.037037
TenC    0.018519
Name: proportion, dtype: float64


Frequency table for SaleType ============
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64

Relative frequency table for SaleType ============
SaleType
WD       0.867808
New      0.083562
COD      0.029452
ConLD    0.006164
ConLI    0.003425
ConLw    0.003425
CWD      0.002740
Oth      0.002055
Con      0.001370
Name: proportion, dtype: float64


Frequency table for SaleCondition ============
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

Relative frequency table for SaleCondition ============
SaleCondition
Normal     0.820548
Partial    0.085616
Abnorml    0.069178
Family     0.013699
Alloca     0.008219
AdjLand    0.002740
Name: proportion, dtype: float64

8. **Using the `Rocket` class which we created as part of the week 7 class activity, we are going to create a new class called shuttle. The shuttle class should inherit all of Rocket's characteristics but has one additional parameter: flights_completed which measures the number of flights the shuttle has completed.
   Define the shuttle class as the child of the rocket class (please define it in the same jupyter notebook which has all of your other HW answers), and then initialize a new instance of your shuttle class. Once you've created a Shuttle, print the following message: "The shuttle is located at (__, __), and has recorded __ flights", filling the blank spaces to reflect the information for the Shuttle you just created.**

In [14]:
import math

In [15]:
class Rocket:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
    def move_rocket(self, move_x=0, move_y=0):
        self.x += move_x
        self.y += move_y
    def calc_distance(self, other_rocket):
        distance = math.sqrt((self.x-other_rocket.x)**2 + (self.y-other_rocket.y)**2)
        return distance

In [16]:
class Shuttle(Rocket):
    def __init__(self, x=0, y=0, flights_completed=0):
        super().__init__(x, y)
        self.flights_completed = flights_completed

In [17]:
shuttle_example = Shuttle(5, 5, 5)
print(f"The shuttle is located at ({shuttle_example.x}, {shuttle_example.y}), and has recorded {shuttle_example.flights_completed} flights")

The shuttle is located at (5, 5), and has recorded 5 flights

9. **Write a single for loop which randomly creates 11 rockets and 11 shuttles using randomly generated integers. Store this output in two separate lists. Once you have your data, use for loops to print the messages you see below. Note you can use the randint() function from the random module (which you can import with the command from random import randint) to randomly generate the characteristics of your Rockets and Shuttles.**

In [18]:
from random import randint

In [19]:
rocket_list = []
shuttle_list = []
for i in range(11):
    rocket_x = randint(0,50)
    rocket_y = randint(0,50)
    
    shuttle_x = randint(0,50)
    shuttle_y = randint(0,50)
    flights = randint(0,50)

    rocket_list.append(Rocket(rocket_x, rocket_y))
    shuttle_list.append(Shuttle(shuttle_x, shuttle_y, flights))

In [20]:
for index, shuttle in enumerate(shuttle_list):
    print(f"Shuttle {index} has completed {shuttle.flights_completed} flights.")

Shuttle 0 has completed 17 flights.
Shuttle 1 has completed 14 flights.
Shuttle 2 has completed 49 flights.
Shuttle 3 has completed 11 flights.
Shuttle 4 has completed 6 flights.
Shuttle 5 has completed 49 flights.
Shuttle 6 has completed 7 flights.
Shuttle 7 has completed 5 flights.
Shuttle 8 has completed 30 flights.
Shuttle 9 has completed 33 flights.
Shuttle 10 has completed 38 flights.

In [21]:
for index, shuttle in enumerate(shuttle_list):
    distance = shuttle.calc_distance(shuttle_list[0])
    print(f"The first shuttle is {distance:.2f} units away from shuttle {index}.")

The first shuttle is 0.00 units away from shuttle 0.
The first shuttle is 17.69 units away from shuttle 1.
The first shuttle is 26.02 units away from shuttle 2.
The first shuttle is 45.65 units away from shuttle 3.
The first shuttle is 40.79 units away from shuttle 4.
The first shuttle is 39.81 units away from shuttle 5.
The first shuttle is 48.47 units away from shuttle 6.
The first shuttle is 50.48 units away from shuttle 7.
The first shuttle is 13.60 units away from shuttle 8.
The first shuttle is 32.14 units away from shuttle 9.
The first shuttle is 19.92 units away from shuttle 10.

In [22]:
for index, shuttle in enumerate(shuttle_list):
    distance = shuttle.calc_distance(rocket_list[index])
    print(f"The first shuttle is {distance:.2f} units away from rocket {index}.")

The first shuttle is 33.84 units away from rocket 0.
The first shuttle is 7.21 units away from rocket 1.
The first shuttle is 25.96 units away from rocket 2.
The first shuttle is 32.89 units away from rocket 3.
The first shuttle is 41.23 units away from rocket 4.
The first shuttle is 25.00 units away from rocket 5.
The first shuttle is 43.46 units away from rocket 6.
The first shuttle is 35.13 units away from rocket 7.
The first shuttle is 40.82 units away from rocket 8.
The first shuttle is 43.42 units away from rocket 9.
The first shuttle is 38.42 units away from rocket 10.